packages:
- chart/
- chart-cairo/
- chart-diagrams/
- chart-tests/
- chart-gtk/
- chart-gtk3/
flags:
#  gtk:
#    # This needs to be set on macOS
#    have-quartz-gtk: true
resolver: lts-23.19
nix:
  packages: [pkgconfig, cairo, zlib, pango, xorg.xproto, xorg.libX11, gtk2, gtk3]
