flags: {}
packages:
- chart/
- chart-cairo/
- chart-diagrams/
- chart-tests/
- chart-gtk/
- chart-gtk3/
#flags:
#  gtk:
#    # This needs to be true on osx
#    have-quartz-gtk: false
resolver: lts-15.3
extra-deps:
- gtk-0.14.9
- gtk3-0.14.9
- gio-0.13.5.0
nix:
  packages: [pkgconfig, cairo, zlib, pango, xorg.xproto, xorg.libX11, gtk2, gtk3]
